CC=gcc
CFLAGS=-std=c99 -Wall -Wextra -Werror -g

proj3: clean
	$(CC) $(CFLAGS) proj3.c -o proj3

test: clean
	$(CC) $(CFLAGS) test.c -o test

float: clean
	$(CC) $(CFLAGS) float.c -o float

clean:
	rm -rf proj3